services:
  api:
    build:
      context: ./backend
      target: base
    container_name: ecommerce-api
    ports:
      - "${PORT_API:-3000}:3000"
    env_file:
      - ./backend/.env
    command: npm run start:dev
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_STRIPE_PUBLIC_KEY=pk_test_51TZMP3FTxaZblzsvSEtnQ2jInbwxaPQBSg5wehNIXdtt2naf8IAWnH1hEISrWX9uyOSo9rxLxM9wHeBZKLuhQMSf00ysk5aHNp
        - VITE_API_URL=http://localhost:3000
    container_name: ecommerce-frontend
    ports:
      - "${PORT_FRONTEND:-5173}:80"
    depends_on:
      - api
